Repository arduino-libraries/Arduino_ConnectionHandler, pull requests merged in 2024-06, with the labels that each got.

#107 Add support for custom Ethernet timeouts
  src/Arduino_EthernetConnectionHandler.cpp
  src/Arduino_EthernetConnectionHandler.h
Labels: type: enhancement, topic: code

#111 chore: Clarify secret usage with comments
  examples/ConnectionHandlerDemo/arduino_secrets.h
Labels: topic: documentation, type: enhancement

#112 chore: LoRa to use BOARD_HAS_LORA
  src/Arduino_LoRaConnectionHandler.cpp
  src/Arduino_LoRaConnectionHandler.h
Labels: type: enhancement, topic: code

#118 Change maintainer to `Arduino <info@arduino.cc>`
  library.properties
Labels: type: enhancement, topic: infrastructure

#119 Add Cellular support for Portenta H7 and Portenta C33
  .github/workflows/compile-examples.yml
  examples/ConnectionHandlerDemo/ConnectionHandlerDemo.ino
  src/Arduino_CellularConnectionHandler.cpp
  src/Arduino_CellularConnectionHandler.h
  src/Arduino_ConnectionHandler.h
Labels: type: enhancement, topic: code

#120 Example fix params order for GSMConnectionHandler and CatM1ConnectionHandler
  examples/ConnectionHandlerDemo/ConnectionHandlerDemo.ino
Labels: type: imperfection, topic: documentation
